### ISSUE TITLE
1

### ISSUE THREAD

**Issue by jaqlai** [johnsmithm/handwritten-sequence-tensorflow#1]
Hi, I tried to run the shell command to initiate training:

python trainer/run.py --input_path data/handwritten-test.tfrecords --input_path_test data/handwritten-test.tfrecords --model_dir models --board_path TFboard --filenameNr 1 --save_step 500  --batch_size 10 --max_steps 1000 --display_step 100

but the process failed. This is the entire shell:

Namespace(batch_size=10, bias=0.1, board_path='TFboard', ctc_decoder='greedy', decay=0.95, display_step=100, distributed=False, filenameNr=1, gpu=False, height=36, hidden=100, initializer='graves', input_path='data/handwritten-test.tfrecords', input_path_test='data/handwritten-test.tfrecords', insertLastState=False, keep_prob=0.8, layers=2, learning_rate=0.0001, max_steps=1000, model_dir='models', momentum=0.9, num_classes=29, optimizer='ADAM', rnn_cell='LSTM', save_step=500, shuffle_batch=False, train=True, width=90)
Traceback (most recent call last):
 File "trainer/run.py", line 647, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "trainer/run.py", line 643, in main
    run_training(args) if args.train else run_sample(args)
  File "trainer/run.py", line 496, in run_training
    model.graphMaker()
  File "trainer/run.py", line 400, in graphMaker
    lambda:[videoInputs_test, seq_len_test, targets_test]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1343, in cond
    (isinstance(x, ops.Tensor) and isinstance(y, ops.Tensor)))
AssertionError

Help please?

**Comment by johnsmithm** [comment]
it is because of the tensorflow version.
i am using  https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0-cp27-none-linux_x86_64.whl
if you need i can give you docker with tensorflow installed.

also you could just delete the tf.cond  and chosse test or train inputs.

**Comment by jaqlai** [comment]
Yes, please! That would be very helpful.

**Comment by johnsmithm** [comment]
try https://github.com/floydhub/dl-docker
